In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)

False

In [4]:
np.nan

nan

In [5]:
3 + np.nan

nan

In [7]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [8]:
a.sum()

nan

In [9]:
a.mean()

nan

In [13]:
3 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

For a numeric array, the `None` value is replaced by `np.nan`:

In [14]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [15]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [16]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [17]:
a.mean()

nan

In [18]:
a.sum()

nan

In [19]:
np.inf

inf

In [20]:
3 + np.inf

inf

In [21]:
np.inf / 3

inf

In [22]:
np.inf / np.inf

nan

In [25]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=float)

In [26]:
b.sum()

nan

In [27]:
np.isnan(np.nan)

True

In [28]:
np.isinf(np.inf)

True

In [29]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [30]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [31]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [33]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

In [34]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [35]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [36]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [37]:
a[np.isfinite(a)].sum()

10.0

In [38]:
a[np.isfinite(a)].mean()

2.5