In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
#np.array([0] * 10) array of size and and filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# numpy array with values ranging from 10 to 49

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# numpy matrix of 2*2 integers filled with ones

In [7]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

In [8]:
# 3*2 float numbers filled with ones

In [10]:
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
#new numpy array with the same shape and type as X filled with ones

In [14]:
X = np.arange(4, dtype=int)
np.ones_like(X)

array([1, 1, 1, 1])

In [16]:
X = np.array([[1,2,3], [4,5,6]], dtype=int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
# numpy matrix of 4*4 integers filled with fives

In [19]:
np.ones([4,4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [21]:
X = np.array([[2,3], [6,2]], dtype=int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [22]:
# 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# 3 random integer values between 1 and 10

In [26]:
np.random.randint(10, size=3)

array([4, 2, 9])

In [27]:
#filled with random float values 
np.random.randn(3,3,3) 

array([[[-0.64755175, -0.49065891,  0.32154486],
        [ 0.45706642, -0.61097255, -1.07838233],
        [-0.54268894, -1.10060705, -0.13136886]],

       [[-0.60139448, -0.54060235, -0.0311807 ],
        [-1.06100389,  1.28718525,  0.59650843],
        [-0.83285654, -0.57029248, -2.1796127 ]],

       [[-1.25103637, -1.52078778, -0.997998  ],
        [ 1.1646271 ,  0.63472966,  0.19115712],
        [-0.13004509, -3.06630204, -0.01336946]]])

In [28]:
# X python list convert it to an Y numpy array

In [29]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [30]:
# X numpy array, make a copy and store it on Y

In [32]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 2531405848208
[5 2 3] 2531406007344


In [33]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# odd numbers between 1 to 10

In [35]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [36]:
#numbers from 1 to 10, in descending order

In [37]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [38]:
# 3*3 numpy matrix filled with values ranging from 0 to 8

In [39]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
#  memory size

In [41]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [ ]:
# show it's first element

In [42]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [ ]:
#show it's last element

In [44]:
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [45]:
#show it's first three elements

In [46]:
X = np.array(['A','B','C','D','E'])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [47]:
# show all middle elements

In [48]:
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [49]:
# elements in reverse position

In [50]:
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [51]:
# show the elements in an odd position

In [52]:
X = np.array(['A','B','C','D','E'])
#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [53]:
# X numpy matrix show the first row elements

In [54]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [55]:
# the last row elements

In [56]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

In [57]:
#  the first element on first row

In [58]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

In [59]:
# show the last element on last row

In [60]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

In [61]:
# how the middle row elements

In [62]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [63]:
# first two elements on the first two rows

In [64]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [65]:
#  last two elements on the last two rows

In [66]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

### Convert the given integer numpy array to float

In [67]:
#Convert the given integer numpy array to float

In [69]:
X = [-5, -3, 0, 10, 40]
np.array(X, float)

array([-5., -3.,  0., 10., 40.])

In [70]:
# reverse

In [71]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

In [72]:
# order

In [73]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

In [74]:
#set the fifth element equal to 1

In [75]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [76]:
# change the 50 with a 40

In [77]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

In [78]:
#change the last row with all 1

In [79]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [80]:
# change the last item on the last row with a 0

In [81]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [82]:
# add 5 to every element

In [83]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [84]:
#mask showing negative elements

In [85]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [86]:
# get the negative elements

In [88]:
mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [ ]:
# numbers higher than 5

In [89]:
mask = X > 5
X[mask]

array([ 6, 10])

In [90]:
# numbers higher than the elements mean

In [93]:
X.mean()

0.9

In [94]:
mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [95]:
# numbers equal to 2 or 10

In [96]:
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [ ]:
#return True if none of its elements is zero

In [97]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

In [98]:
# return True if any of its elements is zero

In [99]:
X.any()

True

In [ ]:
# Summary statistics


In [100]:
#show the sum of its elements

In [101]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

In [102]:
# mean value

In [103]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.mean()

3.7

In [104]:
# sum of its columns

In [106]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [107]:
# mean value of its rows

In [108]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) 

array([ 2.5,  6.5, 10.5, 14.5])

In [109]:
# max value of its elements

In [111]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.max()

10